# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:${LIBSQL_VERSION:-latest}
    container_name: squelify_libsql
    hostname: libsql
    ports:
      - 5001:5001 # gRPC connection
      - 8080:8080 # user HTTP connection
      - 8081:8081 # admin HTTP connection
    volumes:
      - libsql_data:/var/lib/sqld/data
    command: '/bin/sqld --enable-namespaces --enable-http-console'

  mailcrab:
    image: marlonb/mailcrab:latest
    container_name: squelify_mailcrab
    environment:
      SMTP_PORT: 2525 # port number for the SMTP server
      HTTP_PORT: 2580 # port number for the web interface
    ports:
      - 2525:2525 # port the SMTP server should be accessible on
      - 2580:2580 # port the web interface should be accessible on

volumes:
  libsql_data:
    name: squelify_libsql_data
    driver: local
