# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  libsql:
    # libsql://localhost:8080?tls=0
    image: ghcr.io/tursodatabase/libsql-server:latest
    container_name: ntrl_libsql
    hostname: libsql
    ports:
      - 5001:5001 # gRPC connection
      - 8080:8080 # user HTTP connection
      - 8081:8081 # admin HTTP connection
    volumes:
      - libsql_data:/var/lib/sqld/data
    command: '/bin/sqld --enable-namespaces --enable-http-console'

  mailpit:
    image: axllent/mailpit:latest
    container_name: ntrl_mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - 1025:1025 # port the SMTP server should be accessible on
      - 8025:8025 # port the web interface should be accessible on
    environment:
      # https://mailpit.axllent.org/docs/configuration/runtime-options
      # MP_UI_AUTH: 'user1:password1 user2:password2'
      TZ: Asia/Jakarta

volumes:
  libsql_data:
    driver: local
  mailpit_data:
    driver: local
