/**
 * Columns that are generated by the database should be marked using
 * the `Generated` type. This way they are automatically made optional
 * in inserts and updates.
 *
 * You can specify a different type for each operation (select, insert and
 * update) using the `ColumnType<SelectType, InsertType, UpdateType>` wrapper.
 * Here we define a column `updated_at` that is selected as a `Date`, can
 * optionally be provided as a `string` in inserts and can never be updated.
 */

import type { ColumnType, CreateTableBuilder, RawBuilder } from 'kysely'
import { sql } from 'kysely'

export interface WithTimeStampSchema {
  createdAt: ColumnType<Date, string | undefined, never>
  updatedAt: ColumnType<Date, string | undefined, never>
}

export interface WithSoftDeleteSchema {
  deletedAt: ColumnType<Date | null, string | undefined, string | undefined>
}

// Define timestamp formats as constants for reusability
const TIMESTAMP = {
  UNIX: `strftime('%s', 'now')`,
  ISO: `strftime('%Y-%m-%dT%H:%M:%fZ', 'now')`,
} as const

// SQLite-specific function, returns the current Unix timestamp.
export const UNIX_TIMESTAMP = sql.raw(`(${TIMESTAMP.UNIX})`)

// SQLite-specific function, returns the current timestamp in ISO8601 format.
// For zod compatibility, we need to use the ISO8601 format.
// Use this: z.string().datetime({ offset: true })
export const ISO_TIMESTAMP = sql.raw(`(${TIMESTAMP.ISO})`)

export const addColumnTimestamps = <T extends string, C extends string = never>(
  builder: CreateTableBuilder<T, C>
) => {
  return builder
    .addColumn('created_at', 'text', (col) => col.defaultTo(ISO_TIMESTAMP).notNull())
    .addColumn('updated_at', 'text', (col) => col.defaultTo(ISO_TIMESTAMP).notNull())
}

export const addColumnSoftDelete = <T extends string, C extends string = never>(
  builder: CreateTableBuilder<T, C>
) => builder.addColumn('deleted_at', 'text', (col) => col.defaultTo(null))

/* @reference: https://www.kysely.dev/docs/recipes/relations */
export function json<T>(value: T): RawBuilder<T> {
  return sql`CAST(${JSON.stringify(value)} AS JSONB)`
}

export function createTriggerUpdatedAt(table: string, isInternal = false): RawBuilder<string> {
  const triggerName = `${isInternal ? 'sq_' : ''}trg_${table}_updated_at`
  return sql.raw(`CREATE TRIGGER IF NOT EXISTS ${triggerName}
    AFTER UPDATE ON ${table} FOR EACH ROW
    BEGIN
      UPDATE ${table} SET updated_at = ${TIMESTAMP.UNIX}
      WHERE id = NEW.id;
    END;
  `)
}

export function dropTriggerUpdatedAt(table: string, isInternal = false): RawBuilder<string> {
  const triggerName = `${isInternal ? 'sq_' : ''}trg_${table}_updated_at`
  return sql.raw(`DROP TRIGGER IF EXISTS ${triggerName};`)
}
