/**
 * Columns that are generated by the database should be marked using
 * the `Generated` type. This way they are automatically made optional
 * in inserts and updates.
 *
 * You can specify a different type for each operation (select, insert and
 * update) using the `ColumnType<SelectType, InsertType, UpdateType>` wrapper.
 * Here we define a column `updated_at` that is selected as a `Date`, can
 * optionally be provided as a `string` in inserts and can never be updated.
 */

import type { ColumnType, CreateTableBuilder, RawBuilder } from 'kysely'
import { sql } from 'kysely'

export interface WithTimeStampSchema {
  createdAt: ColumnType<Date, string | undefined, never>
  updatedAt: ColumnType<Date, string | undefined, never>
}

export interface WithSoftDeleteSchema {
  deletedAt: ColumnType<Date | null, string | undefined, string | undefined>
}

// Postgres-specific function, returns the current timestamp in ISO8601 format.
// For zod compatibility, we need to use the ISO8601 format.
// Use this: z.string().datetime({ offset: true })
export const ISO_TIMESTAMP = sql`CURRENT_TIMESTAMP`

export const addColumnTimestamps = <T extends string, C extends string = never>(
  builder: CreateTableBuilder<T, C>
) => {
  return builder
    .addColumn('created_at', 'timestamptz', (col) => col.notNull().defaultTo(ISO_TIMESTAMP))
    .addColumn('updated_at', 'timestamptz')
}

export const addColumnSoftDelete = <T extends string, C extends string = never>(
  builder: CreateTableBuilder<T, C>
) => builder.addColumn('deleted_at', 'text', (col) => col.defaultTo(null))

/* @reference: https://www.kysely.dev/docs/recipes/relations */
export function json<T>(value: T): RawBuilder<T> {
  return sql`CAST(${JSON.stringify(value)} AS JSONB)`
}

export function dropTrigger(triggerName: string, tableName: string): RawBuilder<string> {
  return sql.raw(`DROP TRIGGER IF EXISTS ${triggerName} ON ${tableName};`)
}

export function dropTriggerUpdatedAt(schema: string, table: string): RawBuilder<string> {
  return dropTrigger(`trg_${table}_updated_at`, `${schema}.${table}`)
}

export function createTriggerUpdatedAt(schema: string, table: string): RawBuilder<string> {
  return sql.raw(`CREATE TRIGGER trg_${table}_updated_at
    BEFORE UPDATE ON ${schema}.${table} FOR EACH ROW
    EXECUTE FUNCTION fn_updated_at_value();
  `)
}
