import type { ColumnType } from 'kysely'

import type { IAccount } from './schemas/account'
import type { IAuditLog } from './schemas/audit_log'
import type { IEmail } from './schemas/email'
import type { IInvitation } from './schemas/invitation'
import type { IJWK } from './schemas/jwk'
import type { IMember } from './schemas/member'
import type { IOrganization } from './schemas/organization'
import type { IPasskey } from './schemas/passkey'
import type { IPassword } from './schemas/password'
import type { IPermission } from './schemas/permission'
import type { IRateLimit } from './schemas/rate_limit'
import type { IRole } from './schemas/role'
import type { IRolePermission } from './schemas/role_permission'
import type { ISession } from './schemas/session'
import type { ITwoFactor } from './schemas/two_factor'
import type { IUser } from './schemas/user'
import type { IUserBan } from './schemas/user_ban'
import type { IUserMetadata } from './schemas/user_metadata'
import type { IUserRole } from './schemas/user_role'
import type { IVerification } from './schemas/verification'

/**
 * For Kysely's type-safety and autocompletion to work, it needs to know
 * your database structure. This requires a TypeScript Database interface,
 * that contains table names as keys and table schema interfaces as values.
 *
 * @see: https://www.kysely.dev/docs/recipes/schemas
 */
export interface Database {
  sq_accounts: IAccount
  sq_audit_logs: IAuditLog
  sq_emails: IEmail
  sq_invitations: IInvitation
  sq_jwks: IJWK
  sq_members: IMember
  sq_organizations: IOrganization
  sq_passkeys: IPasskey
  sq_passwords: IPassword
  sq_permissions: IPermission
  sq_rate_limits: IRateLimit
  sq_role_permissions: IRolePermission
  sq_roles: IRole
  sq_sessions: ISession
  sq_two_factors: ITwoFactor
  sq_user_roles: IUserRole
  sq_user_bans: IUserBan
  sq_user_metadata: IUserMetadata
  sq_users: IUser
  sq_verifications: IVerification
}

/**
 * Columns that are generated by the database should be marked using
 * the `Generated` type. This way they are automatically made optional
 * in inserts and updates.
 *
 * You can specify a different type for each operation (select, insert and
 * update) using the `ColumnType<SelectType, InsertType, UpdateType>` wrapper.
 * Here we define a column `updated_at` that is selected as a `Date`, can
 * optionally be provided as a `string` in inserts and can never be updated.
 */

export interface WithTimeStampSchema {
  createdAt: ColumnType<Date, string | undefined, never>
  updatedAt: ColumnType<Date, string | undefined, never>
}

export interface WithSoftDeleteSchema {
  deletedAt: ColumnType<Date | null, string | undefined, string | undefined>
}
