import type { ColumnType } from 'kysely'
import type { AccountTable } from './schemas/account'
import type { PasskeyTable } from './schemas/passkey'
import type { RateLimitTable, SessionTable } from './schemas/session'
import type { UserTable } from './schemas/user'
import type { VerificationTable } from './schemas/verification'

/**
 * For Kysely's type-safety and autocompletion to work, it needs to know
 * your database structure. This requires a TypeScript Database interface,
 * that contains table names as keys and table schema interfaces as values.
 */
export interface Database {
  accounts: AccountTable
  passkey: PasskeyTable
  rate_limit: RateLimitTable
  sessions: SessionTable
  users: UserTable
  verifications: VerificationTable
}

/**
 * Columns that are generated by the database should be marked using
 * the `Generated` type. This way they are automatically made optional
 * in inserts and updates.
 *
 * You can specify a different type for each operation (select, insert and
 * update) using the `ColumnType<SelectType, InsertType, UpdateType>` wrapper.
 * Here we define a column `updated_at` that is selected as a `Date`, can
 * optionally be provided as a `string` in inserts and can never be updated.
 */

export interface WithTimeStampSchema {
  createdAt: ColumnType<Date, string | undefined, never>
  updatedAt: ColumnType<Date, string | undefined, never>
}

export interface WithSoftDeleteSchema {
  deletedAt: ColumnType<Date | null, string | undefined, string | undefined>
}
