/**
 * For Kysely's type-safety and autocompletion to work, it needs to know
 * your database structure. This requires a TypeScript Database interface,
 * that contains table names as keys and table schema interfaces as values.
 *
 * @see: https://www.kysely.dev/docs/recipes/schemas
 */

import type { ColumnType } from 'kysely'
import type { IAccount } from './schemas/account'
import type { IApiKey } from './schemas/api_key'
import type { IAuditLog } from './schemas/audit_log'
import type { IEmail } from './schemas/email'
import type { IInvitation } from './schemas/invitation'
import type { IJWK } from './schemas/jwk'
import type { IMember } from './schemas/member'
import type { IOrganization } from './schemas/organization'
import type { IPasskey } from './schemas/passkey'
import type { IPassword } from './schemas/password'
import type { IPermission } from './schemas/permission'
import type { IRateLimit } from './schemas/rate_limit'
import type { IRole } from './schemas/role'
import type { IRolePermission } from './schemas/role_permission'
import type { ISession } from './schemas/session'
import type { ISuperuser } from './schemas/superuser'
import type { ITwoFactor } from './schemas/two_factor'
import type { IUser } from './schemas/user'
import type { IUserBan } from './schemas/user_ban'
import type { IUserMetadata } from './schemas/user_metadata'
import type { IUserRole } from './schemas/user_role'
import type { IVerification } from './schemas/verification'

/**
 * The `AppMigrationSchema` interface defines the schema for the `_migrations`
 * table, which stores information about user defined migrations.
 */
interface AppMigrationSchema {
  _migrations: {
    name: string
    checksum: string
    executedAt: ColumnType<Date, number | undefined, never>
  }
}

/**
 * For Kysely's type-safety and autocompletion to work, it needs to know
 * your database structure. This requires a TypeScript Database interface,
 * that contains table names as keys and table schema interfaces as values.
 *
 * @see: https://www.kysely.dev/docs/recipes/schemas
 */
export interface Database extends AppMigrationSchema {
  _sq_accounts: IAccount
  _sq_api_keys: IApiKey
  _sq_audit_logs: IAuditLog
  _sq_emails: IEmail
  _sq_invitations: IInvitation
  _sq_jwks: IJWK
  _sq_members: IMember
  _sq_organizations: IOrganization
  _sq_passkeys: IPasskey
  _sq_passwords: IPassword
  _sq_permissions: IPermission
  _sq_rate_limits: IRateLimit
  _sq_role_permissions: IRolePermission
  _sq_roles: IRole
  _sq_sessions: ISession
  _sq_superusers: ISuperuser
  _sq_two_factors: ITwoFactor
  _sq_user_bans: IUserBan
  _sq_user_metadata: IUserMetadata
  _sq_user_roles: IUserRole
  _sq_users: IUser
  _sq_verifications: IVerification
}

/**
 * Columns that are generated by the database should be marked using
 * the `Generated` type. This way they are automatically made optional
 * in inserts and updates.
 *
 * You can specify a different type for each operation (select, insert and
 * update) using the `ColumnType<SelectType, InsertType, UpdateType>` wrapper.
 * Here we define a column `updated_at` that is selected as a `Date`, can
 * optionally be provided as a `string` in inserts and can never be updated.
 */
export interface WithTimeStampSchema {
  createdAt: ColumnType<Date, string | undefined, never>
  updatedAt: ColumnType<Date, string | undefined, never>
}

export interface WithSoftDeleteSchema {
  deletedAt: ColumnType<Date | null, string | undefined, string | undefined>
}
